INSERT INTO chinook.public.music_artist (id, name) VALUES (1, N'AC/DC');
INSERT INTO chinook.public.music_artist (id, name) VALUES (2, N'Accept');
INSERT INTO chinook.public.music_artist (id, name) VALUES (3, N'Aerosmith');
INSERT INTO chinook.public.music_artist (id, name) VALUES (4, N'Alanis Morissette');
INSERT INTO chinook.public.music_artist (id, name) VALUES (5, N'Alice In Chains');
INSERT INTO chinook.public.music_artist (id, name) VALUES (6, N'Antônio Carlos Jobim');
INSERT INTO chinook.public.music_artist (id, name) VALUES (7, N'Apocalyptica');
INSERT INTO chinook.public.music_artist (id, name) VALUES (8, N'Audioslave');
INSERT INTO chinook.public.music_artist (id, name) VALUES (9, N'BackBeat');
INSERT INTO chinook.public.music_artist (id, name) VALUES (10, N'Billy Cobham');
INSERT INTO chinook.public.music_artist (id, name) VALUES (11, N'Black Label Society');
INSERT INTO chinook.public.music_artist (id, name) VALUES (12, N'Black Sabbath');
INSERT INTO chinook.public.music_artist (id, name) VALUES (13, N'Body Count');
INSERT INTO chinook.public.music_artist (id, name) VALUES (14, N'Bruce Dickinson');
INSERT INTO chinook.public.music_artist (id, name) VALUES (15, N'Buddy Guy');
INSERT INTO chinook.public.music_artist (id, name) VALUES (16, N'Caetano Veloso');
INSERT INTO chinook.public.music_artist (id, name) VALUES (17, N'Chico Buarque');
INSERT INTO chinook.public.music_artist (id, name) VALUES (18, N'Chico Science & Nação Zumbi');
INSERT INTO chinook.public.music_artist (id, name) VALUES (19, N'Cidade Negra');
INSERT INTO chinook.public.music_artist (id, name) VALUES (20, N'Cláudio Zoli');
INSERT INTO chinook.public.music_artist (id, name) VALUES (21, N'Various Artists');
INSERT INTO chinook.public.music_artist (id, name) VALUES (22, N'Led Zeppelin');
INSERT INTO chinook.public.music_artist (id, name) VALUES (23, N'Frank Zappa & Captain Beefheart');
INSERT INTO chinook.public.music_artist (id, name) VALUES (24, N'Marcos Valle');
INSERT INTO chinook.public.music_artist (id, name) VALUES (25, N'Milton Nascimento & Bebeto');
INSERT INTO chinook.public.music_artist (id, name) VALUES (26, N'Azymuth');
INSERT INTO chinook.public.music_artist (id, name) VALUES (27, N'Gilberto Gil');
INSERT INTO chinook.public.music_artist (id, name) VALUES (28, N'João Gilberto');
INSERT INTO chinook.public.music_artist (id, name) VALUES (29, N'Bebel Gilberto');
INSERT INTO chinook.public.music_artist (id, name) VALUES (30, N'Jorge Vercilo');
INSERT INTO chinook.public.music_artist (id, name) VALUES (31, N'Baby Consuelo');
INSERT INTO chinook.public.music_artist (id, name) VALUES (32, N'Ney Matogrosso');
INSERT INTO chinook.public.music_artist (id, name) VALUES (33, N'Luiz Melodia');
INSERT INTO chinook.public.music_artist (id, name) VALUES (34, N'Nando Reis');
INSERT INTO chinook.public.music_artist (id, name) VALUES (35, N'Pedro Luís & A Parede');
INSERT INTO chinook.public.music_artist (id, name) VALUES (36, N'O Rappa');
INSERT INTO chinook.public.music_artist (id, name) VALUES (37, N'Ed Motta');
INSERT INTO chinook.public.music_artist (id, name) VALUES (38, N'Banda Black Rio');
INSERT INTO chinook.public.music_artist (id, name) VALUES (39, N'Fernanda Porto');
INSERT INTO chinook.public.music_artist (id, name) VALUES (40, N'Os Cariocas');
INSERT INTO chinook.public.music_artist (id, name) VALUES (41, N'Elis Regina');
INSERT INTO chinook.public.music_artist (id, name) VALUES (42, N'Milton Nascimento');
INSERT INTO chinook.public.music_artist (id, name) VALUES (43, N'A Cor Do Som');
INSERT INTO chinook.public.music_artist (id, name) VALUES (44, N'Kid Abelha');
INSERT INTO chinook.public.music_artist (id, name) VALUES (45, N'Sandra De Sá');
INSERT INTO chinook.public.music_artist (id, name) VALUES (46, N'Jorge Ben');
INSERT INTO chinook.public.music_artist (id, name) VALUES (47, N'Hermeto Pascoal');
INSERT INTO chinook.public.music_artist (id, name) VALUES (48, N'Barão Vermelho');
INSERT INTO chinook.public.music_artist (id, name) VALUES (49, N'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto');
INSERT INTO chinook.public.music_artist (id, name) VALUES (50, N'Metallica');
INSERT INTO chinook.public.music_artist (id, name) VALUES (51, N'Queen');
INSERT INTO chinook.public.music_artist (id, name) VALUES (52, N'Kiss');
INSERT INTO chinook.public.music_artist (id, name) VALUES (53, N'Spyro Gyra');
INSERT INTO chinook.public.music_artist (id, name) VALUES (54, N'Green Day');
INSERT INTO chinook.public.music_artist (id, name) VALUES (55, N'David Coverdale');
INSERT INTO chinook.public.music_artist (id, name) VALUES (56, N'Gonzaguinha');
INSERT INTO chinook.public.music_artist (id, name) VALUES (57, N'Os Mutantes');
INSERT INTO chinook.public.music_artist (id, name) VALUES (58, N'Deep Purple');
INSERT INTO chinook.public.music_artist (id, name) VALUES (59, N'Santana');
INSERT INTO chinook.public.music_artist (id, name) VALUES (60, N'Santana Feat. Dave Matthews');
INSERT INTO chinook.public.music_artist (id, name) VALUES (61, N'Santana Feat. Everlast');
INSERT INTO chinook.public.music_artist (id, name) VALUES (62, N'Santana Feat. Rob Thomas');
INSERT INTO chinook.public.music_artist (id, name) VALUES (63, N'Santana Feat. Lauryn Hill & Cee-Lo');
INSERT INTO chinook.public.music_artist (id, name) VALUES (64, N'Santana Feat. The Project G&B');
INSERT INTO chinook.public.music_artist (id, name) VALUES (65, N'Santana Feat. Maná');
INSERT INTO chinook.public.music_artist (id, name) VALUES (66, N'Santana Feat. Eagle-Eye Cherry');
INSERT INTO chinook.public.music_artist (id, name) VALUES (67, N'Santana Feat. Eric Clapton');
INSERT INTO chinook.public.music_artist (id, name) VALUES (68, N'Miles Davis');
INSERT INTO chinook.public.music_artist (id, name) VALUES (69, N'Gene Krupa');
INSERT INTO chinook.public.music_artist (id, name) VALUES (70, N'Toquinho & Vinícius');
INSERT INTO chinook.public.music_artist (id, name) VALUES (71, N'Vinícius De Moraes & Baden Powell');
INSERT INTO chinook.public.music_artist (id, name) VALUES (72, N'Vinícius De Moraes');
INSERT INTO chinook.public.music_artist (id, name) VALUES (73, N'Vinícius E Qurteto Em Cy');
INSERT INTO chinook.public.music_artist (id, name) VALUES (74, N'Vinícius E Odette Lara');
INSERT INTO chinook.public.music_artist (id, name) VALUES (75, N'Vinicius, Toquinho & Quarteto Em Cy');
INSERT INTO chinook.public.music_artist (id, name) VALUES (76, N'Creedence Clearwater Revival');
INSERT INTO chinook.public.music_artist (id, name) VALUES (77, N'Cássia Eller');
INSERT INTO chinook.public.music_artist (id, name) VALUES (78, N'Def Leppard');
INSERT INTO chinook.public.music_artist (id, name) VALUES (79, N'Dennis Chambers');
INSERT INTO chinook.public.music_artist (id, name) VALUES (80, N'Djavan');
INSERT INTO chinook.public.music_artist (id, name) VALUES (81, N'Eric Clapton');
INSERT INTO chinook.public.music_artist (id, name) VALUES (82, N'Faith No More');
INSERT INTO chinook.public.music_artist (id, name) VALUES (83, N'Falamansa');
INSERT INTO chinook.public.music_artist (id, name) VALUES (84, N'Foo Fighters');
INSERT INTO chinook.public.music_artist (id, name) VALUES (85, N'Frank Sinatra');
INSERT INTO chinook.public.music_artist (id, name) VALUES (86, N'Funk Como Le Gusta');
INSERT INTO chinook.public.music_artist (id, name) VALUES (87, N'Godsmack');
INSERT INTO chinook.public.music_artist (id, name) VALUES (88, N'Guns N'' Roses');
INSERT INTO chinook.public.music_artist (id, name) VALUES (89, N'Incognito');
INSERT INTO chinook.public.music_artist (id, name) VALUES (90, N'Iron Maiden');
INSERT INTO chinook.public.music_artist (id, name) VALUES (91, N'James Brown');
INSERT INTO chinook.public.music_artist (id, name) VALUES (92, N'Jamiroquai');
INSERT INTO chinook.public.music_artist (id, name) VALUES (93, N'JET');
INSERT INTO chinook.public.music_artist (id, name) VALUES (94, N'Jimi Hendrix');
INSERT INTO chinook.public.music_artist (id, name) VALUES (95, N'Joe Satriani');
INSERT INTO chinook.public.music_artist (id, name) VALUES (96, N'Jota Quest');
INSERT INTO chinook.public.music_artist (id, name) VALUES (97, N'João Suplicy');
INSERT INTO chinook.public.music_artist (id, name) VALUES (98, N'Judas Priest');
INSERT INTO chinook.public.music_artist (id, name) VALUES (99, N'Legião Urbana');
INSERT INTO chinook.public.music_artist (id, name) VALUES (100, N'Lenny Kravitz');
INSERT INTO chinook.public.music_artist (id, name) VALUES (101, N'Lulu Santos');
INSERT INTO chinook.public.music_artist (id, name) VALUES (102, N'Marillion');
INSERT INTO chinook.public.music_artist (id, name) VALUES (103, N'Marisa Monte');
INSERT INTO chinook.public.music_artist (id, name) VALUES (104, N'Marvin Gaye');
INSERT INTO chinook.public.music_artist (id, name) VALUES (105, N'Men At Work');
INSERT INTO chinook.public.music_artist (id, name) VALUES (106, N'Motörhead');
INSERT INTO chinook.public.music_artist (id, name) VALUES (107, N'Motörhead & Girlschool');
INSERT INTO chinook.public.music_artist (id, name) VALUES (108, N'Mônica Marianno');
INSERT INTO chinook.public.music_artist (id, name) VALUES (109, N'Mötley Crüe');
INSERT INTO chinook.public.music_artist (id, name) VALUES (110, N'Nirvana');
INSERT INTO chinook.public.music_artist (id, name) VALUES (111, N'O Terço');
INSERT INTO chinook.public.music_artist (id, name) VALUES (112, N'Olodum');
INSERT INTO chinook.public.music_artist (id, name) VALUES (113, N'Os Paralamas Do Sucesso');
INSERT INTO chinook.public.music_artist (id, name) VALUES (114, N'Ozzy Osbourne');
INSERT INTO chinook.public.music_artist (id, name) VALUES (115, N'Page & Plant');
INSERT INTO chinook.public.music_artist (id, name) VALUES (116, N'Passengers');
INSERT INTO chinook.public.music_artist (id, name) VALUES (117, N'Paul D''Ianno');
INSERT INTO chinook.public.music_artist (id, name) VALUES (118, N'Pearl Jam');
INSERT INTO chinook.public.music_artist (id, name) VALUES (119, N'Peter Tosh');
INSERT INTO chinook.public.music_artist (id, name) VALUES (120, N'Pink Floyd');
INSERT INTO chinook.public.music_artist (id, name) VALUES (121, N'Planet Hemp');
INSERT INTO chinook.public.music_artist (id, name) VALUES (122, N'R.E.M. Feat. Kate Pearson');
INSERT INTO chinook.public.music_artist (id, name) VALUES (123, N'R.E.M. Feat. KRS-One');
INSERT INTO chinook.public.music_artist (id, name) VALUES (124, N'R.E.M.');
INSERT INTO chinook.public.music_artist (id, name) VALUES (125, N'Raimundos');
INSERT INTO chinook.public.music_artist (id, name) VALUES (126, N'Raul Seixas');
INSERT INTO chinook.public.music_artist (id, name) VALUES (127, N'Red Hot Chili Peppers');
INSERT INTO chinook.public.music_artist (id, name) VALUES (128, N'Rush');
INSERT INTO chinook.public.music_artist (id, name) VALUES (129, N'Simply Red');
INSERT INTO chinook.public.music_artist (id, name) VALUES (130, N'Skank');
INSERT INTO chinook.public.music_artist (id, name) VALUES (131, N'Smashing Pumpkins');
INSERT INTO chinook.public.music_artist (id, name) VALUES (132, N'Soundgarden');
INSERT INTO chinook.public.music_artist (id, name) VALUES (133, N'Stevie Ray Vaughan & Double Trouble');
INSERT INTO chinook.public.music_artist (id, name) VALUES (134, N'Stone Temple Pilots');
INSERT INTO chinook.public.music_artist (id, name) VALUES (135, N'System Of A Down');
INSERT INTO chinook.public.music_artist (id, name) VALUES (136, N'Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO chinook.public.music_artist (id, name) VALUES (137, N'The Black Crowes');
INSERT INTO chinook.public.music_artist (id, name) VALUES (138, N'The Clash');
INSERT INTO chinook.public.music_artist (id, name) VALUES (139, N'The Cult');
INSERT INTO chinook.public.music_artist (id, name) VALUES (140, N'The Doors');
INSERT INTO chinook.public.music_artist (id, name) VALUES (141, N'The Police');
INSERT INTO chinook.public.music_artist (id, name) VALUES (142, N'The Rolling Stones');
INSERT INTO chinook.public.music_artist (id, name) VALUES (143, N'The Tea Party');
INSERT INTO chinook.public.music_artist (id, name) VALUES (144, N'The Who');
INSERT INTO chinook.public.music_artist (id, name) VALUES (145, N'Tim Maia');
INSERT INTO chinook.public.music_artist (id, name) VALUES (146, N'Titãs');
INSERT INTO chinook.public.music_artist (id, name) VALUES (147, N'Battlestar Galactica');
INSERT INTO chinook.public.music_artist (id, name) VALUES (148, N'Heroes');
INSERT INTO chinook.public.music_artist (id, name) VALUES (149, N'Lost');
INSERT INTO chinook.public.music_artist (id, name) VALUES (150, N'U2');
INSERT INTO chinook.public.music_artist (id, name) VALUES (151, N'UB40');
INSERT INTO chinook.public.music_artist (id, name) VALUES (152, N'Van Halen');
INSERT INTO chinook.public.music_artist (id, name) VALUES (153, N'Velvet Revolver');
INSERT INTO chinook.public.music_artist (id, name) VALUES (154, N'Whitesnake');
INSERT INTO chinook.public.music_artist (id, name) VALUES (155, N'Zeca Pagodinho');
INSERT INTO chinook.public.music_artist (id, name) VALUES (156, N'The Office');
INSERT INTO chinook.public.music_artist (id, name) VALUES (157, N'Dread Zeppelin');
INSERT INTO chinook.public.music_artist (id, name) VALUES (158, N'Battlestar Galactica (Classic)');
INSERT INTO chinook.public.music_artist (id, name) VALUES (159, N'Aquaman');
INSERT INTO chinook.public.music_artist (id, name) VALUES (160, N'Christina Aguilera featuring BigElf');
INSERT INTO chinook.public.music_artist (id, name) VALUES (161, N'Aerosmith & Sierra Leone''s Refugee Allstars');
INSERT INTO chinook.public.music_artist (id, name) VALUES (162, N'Los Lonely Boys');
INSERT INTO chinook.public.music_artist (id, name) VALUES (163, N'Corinne Bailey Rae');
INSERT INTO chinook.public.music_artist (id, name) VALUES (164, N'Dhani Harrison & Jakob Dylan');
INSERT INTO chinook.public.music_artist (id, name) VALUES (165, N'Jackson Browne');
INSERT INTO chinook.public.music_artist (id, name) VALUES (166, N'Avril Lavigne');
INSERT INTO chinook.public.music_artist (id, name) VALUES (167, N'Big & Rich');
INSERT INTO chinook.public.music_artist (id, name) VALUES (168, N'Youssou N''Dour');
INSERT INTO chinook.public.music_artist (id, name) VALUES (169, N'Black Eyed Peas');
INSERT INTO chinook.public.music_artist (id, name) VALUES (170, N'Jack Johnson');
INSERT INTO chinook.public.music_artist (id, name) VALUES (171, N'Ben Harper');
INSERT INTO chinook.public.music_artist (id, name) VALUES (172, N'Snow Patrol');
INSERT INTO chinook.public.music_artist (id, name) VALUES (173, N'Matisyahu');
INSERT INTO chinook.public.music_artist (id, name) VALUES (174, N'The Postal Service');
INSERT INTO chinook.public.music_artist (id, name) VALUES (175, N'Jaguares');
INSERT INTO chinook.public.music_artist (id, name) VALUES (176, N'The Flaming Lips');
INSERT INTO chinook.public.music_artist (id, name) VALUES (177, N'Jack''s Mannequin & Mick Fleetwood');
INSERT INTO chinook.public.music_artist (id, name) VALUES (178, N'Regina Spektor');
INSERT INTO chinook.public.music_artist (id, name) VALUES (179, N'Scorpions');
INSERT INTO chinook.public.music_artist (id, name) VALUES (180, N'House Of Pain');
INSERT INTO chinook.public.music_artist (id, name) VALUES (181, N'Xis');
INSERT INTO chinook.public.music_artist (id, name) VALUES (182, N'Nega Gizza');
INSERT INTO chinook.public.music_artist (id, name) VALUES (183, N'Gustavo & Andres Veiga & Salazar');
INSERT INTO chinook.public.music_artist (id, name) VALUES (184, N'Rodox');
INSERT INTO chinook.public.music_artist (id, name) VALUES (185, N'Charlie Brown Jr.');
INSERT INTO chinook.public.music_artist (id, name) VALUES (186, N'Pedro Luís E A Parede');
INSERT INTO chinook.public.music_artist (id, name) VALUES (187, N'Los Hermanos');
INSERT INTO chinook.public.music_artist (id, name) VALUES (188, N'Mundo Livre S/A');
INSERT INTO chinook.public.music_artist (id, name) VALUES (189, N'Otto');
INSERT INTO chinook.public.music_artist (id, name) VALUES (190, N'Instituto');
INSERT INTO chinook.public.music_artist (id, name) VALUES (191, N'Nação Zumbi');
INSERT INTO chinook.public.music_artist (id, name) VALUES (192, N'DJ Dolores & Orchestra Santa Massa');
INSERT INTO chinook.public.music_artist (id, name) VALUES (193, N'Seu Jorge');
INSERT INTO chinook.public.music_artist (id, name) VALUES (194, N'Sabotage E Instituto');
INSERT INTO chinook.public.music_artist (id, name) VALUES (195, N'Stereo Maracana');
INSERT INTO chinook.public.music_artist (id, name) VALUES (196, N'Cake');
INSERT INTO chinook.public.music_artist (id, name) VALUES (197, N'Aisha Duo');
INSERT INTO chinook.public.music_artist (id, name) VALUES (198, N'Habib Koité and Bamada');
INSERT INTO chinook.public.music_artist (id, name) VALUES (199, N'Karsh Kale');
INSERT INTO chinook.public.music_artist (id, name) VALUES (200, N'The Posies');
INSERT INTO chinook.public.music_artist (id, name) VALUES (201, N'Luciana Souza/Romero Lubambo');
INSERT INTO chinook.public.music_artist (id, name) VALUES (202, N'Aaron Goldberg');
INSERT INTO chinook.public.music_artist (id, name) VALUES (203, N'Nicolaus Esterhazy Sinfonia');
INSERT INTO chinook.public.music_artist (id, name) VALUES (204, N'Temple of the Dog');
INSERT INTO chinook.public.music_artist (id, name) VALUES (205, N'Chris Cornell');
INSERT INTO chinook.public.music_artist (id, name) VALUES (206, N'Alberto Turco & Nova Schola Gregoriana');
INSERT INTO chinook.public.music_artist (id, name) VALUES (207, N'Richard Marlow & The Choir of Trinity College, Cambridge');
INSERT INTO chinook.public.music_artist (id, name) VALUES (208, N'English Concert & Trevor Pinnock');
INSERT INTO chinook.public.music_artist (id, name) VALUES (209, N'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO chinook.public.music_artist (id, name) VALUES (210, N'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer');
INSERT INTO chinook.public.music_artist (id, name) VALUES (211, N'Wilhelm Kempff');
INSERT INTO chinook.public.music_artist (id, name) VALUES (212, N'Yo-Yo Ma');
INSERT INTO chinook.public.music_artist (id, name) VALUES (213, N'Scholars Baroque Ensemble');
INSERT INTO chinook.public.music_artist (id, name) VALUES (214, N'Academy of St. Martin in the Fields & Sir Neville Marriner');
INSERT INTO chinook.public.music_artist (id, name) VALUES (215, N'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner');
INSERT INTO chinook.public.music_artist (id, name) VALUES (216, N'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer');
INSERT INTO chinook.public.music_artist (id, name) VALUES (217, N'Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO chinook.public.music_artist (id, name) VALUES (218, N'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner');
INSERT INTO chinook.public.music_artist (id, name) VALUES (219, N'Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO chinook.public.music_artist (id, name) VALUES (220, N'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti');
INSERT INTO chinook.public.music_artist (id, name) VALUES (221, N'Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO chinook.public.music_artist (id, name) VALUES (222, N'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair');
INSERT INTO chinook.public.music_artist (id, name) VALUES (223, N'London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO chinook.public.music_artist (id, name) VALUES (224, N'Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO chinook.public.music_artist (id, name) VALUES (225, N'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker');
INSERT INTO chinook.public.music_artist (id, name) VALUES (226, N'Eugene Ormandy');
INSERT INTO chinook.public.music_artist (id, name) VALUES (227, N'Luciano Pavarotti');
INSERT INTO chinook.public.music_artist (id, name) VALUES (228, N'Leonard Bernstein & New York Philharmonic');
INSERT INTO chinook.public.music_artist (id, name) VALUES (229, N'Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO chinook.public.music_artist (id, name) VALUES (230, N'Aaron Copland & London Symphony Orchestra');
INSERT INTO chinook.public.music_artist (id, name) VALUES (231, N'Ton Koopman');
INSERT INTO chinook.public.music_artist (id, name) VALUES (232, N'Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO chinook.public.music_artist (id, name) VALUES (233, N'Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO chinook.public.music_artist (id, name) VALUES (234, N'Orchestra of The Age of Enlightenment');
INSERT INTO chinook.public.music_artist (id, name) VALUES (235, N'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra');
INSERT INTO chinook.public.music_artist (id, name) VALUES (236, N'James Levine');
INSERT INTO chinook.public.music_artist (id, name) VALUES (237, N'Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO chinook.public.music_artist (id, name) VALUES (238, N'Maurizio Pollini');
INSERT INTO chinook.public.music_artist (id, name) VALUES (239, N'Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett');
INSERT INTO chinook.public.music_artist (id, name) VALUES (240, N'Gustav Mahler');
INSERT INTO chinook.public.music_artist (id, name) VALUES (241, N'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos');
INSERT INTO chinook.public.music_artist (id, name) VALUES (242, N'Edo de Waart & San Francisco Symphony');
INSERT INTO chinook.public.music_artist (id, name) VALUES (243, N'Antal Doráti & London Symphony Orchestra');
INSERT INTO chinook.public.music_artist (id, name) VALUES (244, N'Choir Of Westminster Abbey & Simon Preston');
INSERT INTO chinook.public.music_artist (id, name) VALUES (245, N'Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO chinook.public.music_artist (id, name) VALUES (246, N'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO chinook.public.music_artist (id, name) VALUES (247, N'The King''s Singers');
INSERT INTO chinook.public.music_artist (id, name) VALUES (248, N'Berliner Philharmoniker & Herbert Von Karajan');
INSERT INTO chinook.public.music_artist (id, name) VALUES (249, N'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker');
INSERT INTO chinook.public.music_artist (id, name) VALUES (250, N'Christopher O''Riley');
INSERT INTO chinook.public.music_artist (id, name) VALUES (251, N'Fretwork');
INSERT INTO chinook.public.music_artist (id, name) VALUES (252, N'Amy Winehouse');
INSERT INTO chinook.public.music_artist (id, name) VALUES (253, N'Calexico');
INSERT INTO chinook.public.music_artist (id, name) VALUES (254, N'Otto Klemperer & Philharmonia Orchestra');
INSERT INTO chinook.public.music_artist (id, name) VALUES (255, N'Yehudi Menuhin');
INSERT INTO chinook.public.music_artist (id, name) VALUES (256, N'Philharmonia Orchestra & Sir Neville Marriner');
INSERT INTO chinook.public.music_artist (id, name) VALUES (257, N'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart');
INSERT INTO chinook.public.music_artist (id, name) VALUES (258, N'Les Arts Florissants & William Christie');
INSERT INTO chinook.public.music_artist (id, name) VALUES (259, N'The 12 Cellists of The Berlin Philharmonic');
INSERT INTO chinook.public.music_artist (id, name) VALUES (260, N'Adrian Leaper & Doreen de Feis');
INSERT INTO chinook.public.music_artist (id, name) VALUES (261, N'Roger Norrington, London Classical Players');
INSERT INTO chinook.public.music_artist (id, name) VALUES (262, N'Charles Dutoit & L''Orchestre Symphonique de Montréal');
INSERT INTO chinook.public.music_artist (id, name) VALUES (263, N'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir');
INSERT INTO chinook.public.music_artist (id, name) VALUES (264, N'Kent Nagano and Orchestre de l''Opéra de Lyon');
INSERT INTO chinook.public.music_artist (id, name) VALUES (265, N'Julian Bream');
INSERT INTO chinook.public.music_artist (id, name) VALUES (266, N'Martin Roscoe');
INSERT INTO chinook.public.music_artist (id, name) VALUES (267, N'Göteborgs Symfoniker & Neeme Järvi');
INSERT INTO chinook.public.music_artist (id, name) VALUES (268, N'Itzhak Perlman');
INSERT INTO chinook.public.music_artist (id, name) VALUES (269, N'Michele Campanella');
INSERT INTO chinook.public.music_artist (id, name) VALUES (270, N'Gerald Moore');
INSERT INTO chinook.public.music_artist (id, name) VALUES (271, N'Mela Tenenbaum, Pro Musica Prague & Richard Kapp');
INSERT INTO chinook.public.music_artist (id, name) VALUES (272, N'Emerson String Quartet');
INSERT INTO chinook.public.music_artist (id, name) VALUES (273, N'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu');
INSERT INTO chinook.public.music_artist (id, name) VALUES (274, N'Nash Ensemble');
INSERT INTO chinook.public.music_artist (id, name) VALUES (275, N'Philip Glass Ensemble');
