INSERT INTO chinook.public.music_genre (id, name) VALUES (1, N'Rock');
INSERT INTO chinook.public.music_genre (id, name) VALUES (2, N'Jazz');
INSERT INTO chinook.public.music_genre (id, name) VALUES (3, N'Metal');
INSERT INTO chinook.public.music_genre (id, name) VALUES (4, N'Alternative & Punk');
INSERT INTO chinook.public.music_genre (id, name) VALUES (5, N'Rock And Roll');
INSERT INTO chinook.public.music_genre (id, name) VALUES (6, N'Blues');
INSERT INTO chinook.public.music_genre (id, name) VALUES (7, N'Latin');
INSERT INTO chinook.public.music_genre (id, name) VALUES (8, N'Reggae');
INSERT INTO chinook.public.music_genre (id, name) VALUES (9, N'Pop');
INSERT INTO chinook.public.music_genre (id, name) VALUES (10, N'Soundtrack');
INSERT INTO chinook.public.music_genre (id, name) VALUES (11, N'Bossa Nova');
INSERT INTO chinook.public.music_genre (id, name) VALUES (12, N'Easy Listening');
INSERT INTO chinook.public.music_genre (id, name) VALUES (13, N'Heavy Metal');
INSERT INTO chinook.public.music_genre (id, name) VALUES (14, N'R&B/Soul');
INSERT INTO chinook.public.music_genre (id, name) VALUES (15, N'Electronica/Dance');
INSERT INTO chinook.public.music_genre (id, name) VALUES (16, N'World');
INSERT INTO chinook.public.music_genre (id, name) VALUES (17, N'Hip Hop/Rap');
INSERT INTO chinook.public.music_genre (id, name) VALUES (18, N'Science Fiction');
INSERT INTO chinook.public.music_genre (id, name) VALUES (19, N'TV Shows');
INSERT INTO chinook.public.music_genre (id, name) VALUES (20, N'Sci Fi & Fantasy');
INSERT INTO chinook.public.music_genre (id, name) VALUES (21, N'Drama');
INSERT INTO chinook.public.music_genre (id, name) VALUES (22, N'Comedy');
INSERT INTO chinook.public.music_genre (id, name) VALUES (23, N'Alternative');
INSERT INTO chinook.public.music_genre (id, name) VALUES (24, N'Classical');
INSERT INTO chinook.public.music_genre (id, name) VALUES (25, N'Opera');

INSERT INTO chinook.public.music_mediatype (id, name) VALUES (1, N'MPEG audio file');
INSERT INTO chinook.public.music_mediatype (id, name) VALUES (2, N'Protected AAC audio file');
INSERT INTO chinook.public.music_mediatype (id, name) VALUES (3, N'Protected MPEG-4 video file');
INSERT INTO chinook.public.music_mediatype (id, name) VALUES (4, N'Purchased AAC audio file');
INSERT INTO chinook.public.music_mediatype (id, name) VALUES (5, N'AAC audio file');
